### PR TITLE
Update translations.csv

### PR DESCRIPTION
**Pull request by DeepseaXX**
Add Simplified Chinese up to current version

And if it is OK to encode with 'GB2312' ?
Totally we usd UTF-8, and if you want to change it or something, please let me know.

### CODE REVIEW

**Comment by img02** [comment]
I think it's best to use utf8, I'm not familiar with GB2312 and I don't know if I would need to add some conversion?

To be honest, the simlified chinese does not display properly on my computer, I don't think I have the language pack installed or something.

image

But I guess it works because no one has complain lol

**Comment by DeepseaXX** [comment]
The text encoding issue, I think all you need to do is change the file encoding to UTF-8, and that should solve it. 

GB2312 is a Chinese standard that may cause display problems on computers that don't have Chinese as the default language. Even Chinese developers usually don't use GB2312 due to compatibility issues. 


The issue of not being able to display Chinese characters correctly in games, it's actually quite common. People who want to see Chinese characters properly on non-Chinese servers usually add extra fonts to fix it by themselves, so no need to worry. 

The reason why some characters can't be displayed correctly is probably because the FFXIV font library only supports 'JEGF', so most Chinese characters won't show up right. The ones that do show up are probably because they have the exact same characters in Japanese. 

The Chinese server is separate and a bit behind other regions. But during major updates in the FFXIV game, the developers in charge of the Chinese-version Dalamud will fork and sync the plugin library from the international servers (what we call to distinguish from ours). So, all those files related to multiple languages will be synced to the Chinese-version Dalamud, and then everything will display correctly. I'll include some pictures later to show you what I mean.

**Comment by DeepseaXX** [comment]
I thhink that it might be the first time I use Excel to open this file, and Microsoft thinks I would like to usd GB2312, and changed it.

If it's better to resave by UTF-8 and update it? But it's easy to do it by vscode

**Comment by img02** [comment]
I think currently it's fine. Everything is showing properly when I use notepad++
image

**Comment by DeepseaXX** [comment]
OK then I will do it until next time something new coming.

**Pull request merged**
